### ISSUE TITLE
[BUG] Missing Fiddlestics image on ddragon

### ISSUE THREAD

**Issue by youdidnt** [RiotGames/developer-relations#731] opened 2023-01-24 13:00 UTC
**Bug Description**  
After Fiddlestics rework his image stopped loading. Website is returning 403 error [here](https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Fiddlesticks_0.jpg). Images for other champions like [Karma](https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Karma_0.jpg), [Annie](https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Annie_0.jpg) or [Xin Zhao](https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/XinZhao_0.jpg) working fine, but problem is only with Fiddlestics.

**Problem Description**  
Image is not loading.

**Expected Result**  
Loading Fiddlestics image.

**Actual Result**  
403 error

**Developer Impact**  
The image is not showing up for viewers who I'm showing up this image.

**Player Impact**  
None

**Preconditions**  
What conditions must be met in order for this bug to occur?

* It must be Fiddlestics image

**Repro Steps**  
Step by step, what do you need to do to cause the bug? Note that GitHub will automagically number each step if you prefix the line with "1. "

1. Go to https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Fiddlesticks_0.jpg
1. See the result

**Issue Comments**  
Might want to leave this as instructions for any replies to your issue:

If you're also experiencing this issue please add any additional context that is useful, the developer impact to yourself, and the player impact to your users. As an example, if spectator-v4 isn't working it might affect a scouting site, but it could also affect a mobile app or site to share replays. Give the context on how this issue affects your project.

**Comment by geozukunft** [comment] 2023-01-24 13:16
You need to use the champions key not the name for Fiddlesticks the key is `FiddleSticks` https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/FiddleSticks_0.jpg

**Comment by bangingheads** [comment] 2023-01-24 14:09
Duplicate of #83 
Duplicate of #580 
Duplicate of #693

**Comment by TheDrone7** [comment] 2023-01-24 15:27
#83 holy crap this has been an issue for a long time.

**Comment by geozukunft** [comment] 2023-01-26 09:21
And they are all in turn related to #7 which mentions how to deal with this and that it is considered as feature and not a bug

**Comment by tisbells** [comment] 2023-07-25 16:00
Closing as this is a duplicate of https://github.com/RiotGames/developer-relations/issues/83

**Closed by tisbells** 2023-07-25 16:00 UTC
Labels: closed: duplicate
