### ISSUE TITLE
[BUG][Tournament-v4] Stats callbacks are not being sent after completed games / matches

### ISSUE THREAD

**Issue by slgbrandonwilliams** [RiotGames/developer-relations#152] opened 2019-08-19 17:02 UTC
**Summary**
It seemed that several consumers stopped receiving callbacks from the RIOT API after games played on or around Wednesday (8.14.2019), but the callbacks were working on Tuesday (8.13.2019). 

**Steps to Reproduce**
1. Generate a tournamentId w/ a valid callback URL that can receive callbacks, ie: RequestBin
2. Create a providerId + t-codes w/ above tournamentId.
3. Play a game with t-codes
4. Notice that the callback does not come via the valid URL, but stats are available via the Match API for the game played via the t-code generated above

**Expected Result**
Expecting a callback from RIOT w/ stats to the callback URL provided in the creation of the providerId after a game is played 

**Actual Result**
Consumers are not receiving callbacks after games played. 

**Reproduction Rate**
100% (40/40) 

**Notes:**
Please let me know if you'd like me to reproduce on demand. 

**Severity:**
High

**Comment by castanhob** [comment] 2019-08-19 17:32
Can confirm. We had the same issue around Wenesday (8/14/2019) where we did not receive the callback. Also, on Tuesday (8/13/2019), our endpoint was receiving the callback normally.

I can provide more information as needed.

**Comment by RiotTuxedo** [comment] 2019-08-20 22:56
@slgbrandonwilliams I might have to take you up on that reproduce on demand. Mind adding me on Twitter @RiotTuxedo and I'll follow up with you in a DM.

If anyone is experiencing this issue please provide your providerId, tournament code, and region where the match was played, and the rough time when the match ended.

**Comment by RiotTuxedo** [comment] 2019-08-20 23:48
As an update, we think we might have identified the source of the issue. We're continuing to investigate.

**Comment by omeltchuk** [comment] 2019-08-21 12:35
> If anyone is experiencing this issue please provide your providerId, tournament code, and region where the match was played, and the rough time when the match ended.

providerId: 1715
tournament code: RU046d1-7241c3a5-e3ea-4c8a-9ac1-391fe68fd438
region: RU
match ended: 08-21-2019 15:33:19 Europe/Kiev

**Comment by RiotTuxedo** [comment] 2019-08-22 20:50
A fix has been deployed, if you're still not getting callbacks, same deal. Please provide the following information:

* providerId
* tournament code
* region where the match was played
* the rough time when the match ended

I'll leave this ticket open for a couple days and if there are no further reports, I'll close it out.

**Comment by castanhob** [comment] 2019-08-23 12:16
@RiotTuxedo @slgbrandonwilliams @omeltchuk 

Made a new test today, and received the callback as intended! :tada: 

providerId: 11764
tournamentId: 563932
region: BR
match ended: 08-23-2019 08:37:47 (Brasilia)

Good stuff :+1:

**Comment by RiotTuxedo** [comment] 2019-08-30 02:56
Going to go ahead and close this one out. Feel free to create a new ticket if the issue comes up again.

**Closed by RiotTuxedo** 2019-08-30 02:56 UTC
Labels: api: tournament-v4, closed: resolved, topic: underlying service, type: bug report
