### ISSUE TITLE
[BUG]  Callbacks from endpoints fail

### ISSUE THREAD

**Issue by nexusacademypro** [RiotGames/developer-relations#796] opened 2023-08-01 03:08 UTC
**Bug Description**  
Hello , the endpoint match dont is return the callback to know winners and losers.
How can fix it ?

**Problem Description**  
Hello , the endpoint match dont is return the callback to know winners and losers.
How can fix it ?

**Expected Result**  
I hope the API will display the match results.

**Actual Result**  
There is no return of values, we even have an open ticket in the system https://developer.riotgames.com/ but since April we have not received a response from the resolution of this problem.

**Developer Impact**  
The development of our application has been stopped since April/2023 and the impact on our project is very big.

All application programming is within the terms of RioT

**Player Impact**  
We are still developing our application with the League of Legends API, we don't have players on the platform yet, we are just testing it internally, however, without this functionality, this makes our project unfeasible.

**Preconditions**  
To identify the error, just create a game, play and wait for the result at the end, which is not displayed.

**Comment by geozukunft** [comment] 2023-08-01 08:11
Are you talking about custom games (which by design will not show up) because match-v5 works without any issues in serving played games

**Comment by nexusacademypro** [comment] 2023-08-01 12:53
Hi Viktor, so are you confirming to me that in custom matches match-v5
doesn't return player results?
If I create a match from my system won't match-v5 return the match results?

Regards,

Eros Vasconcelos.

Em ter., 1 de ago. de 2023 às 05:11, Viktor geozukunft <
***@***.***> escreveu:

**Comment by geozukunft** [comment] 2023-08-01 13:09
Correct custom matches by design will not show up in a players match history nor can they be queried if you know the matchId. If you want to run custom games and be able to retrieve the data you want to use the tournament-v4 endpoint that will give you tournament codes which the players can use and those games you can query.

**Comment by nexusacademypro** [comment] 2023-08-01 20:18
Viktor, I got a response from RioT through via the ticket system and there
they informed me that there is still no forecast for the problem. This same
problem is occurring in other systems and there are open tickets here on
GitHub, as you can see in the following link.

 https://github.com/RiotGames/developer-relations/issues/762

Regards,

Eros

Em ter., 1 de ago. de 2023 às 10:33, Eros V ***@***.***> escreveu:

**Comment by geozukunft** [comment] 2023-08-01 20:25
You can just query the player using match-v5 and filter for type TOURNEY and then check the tournament-id as part of the matches response

**Comment by tisbells** [comment] 2023-12-22 19:38
Closing this out as callbacks are working as expected. Feel free to reopen if you continue experiencing issues.

**Closed by tisbells** 2023-12-22 19:38 UTC
