### ISSUE TITLE
[BUG] spectator-v4/GET_getCurrentGameInfoBySummoner return unencrypted puuid

### ISSUE THREAD

**Issue by AoshiW** [RiotGames/developer-relations#880] opened 2024-01-16 17:47 UTC
**Expected Result**  
ecrypted puuid

**Actual Result**  
unecrypted puuid

**Comment by f3ar161** [comment] 2024-01-16 20:21
@AoshiW is fixed

**Comment by AoshiW** [comment] 2024-01-16 20:34
is now encrypted, but in a bad way.
![image](https://github.com/RiotGames/developer-relations/assets/48525283/02fcf217-bff4-43b6-9e5e-5aa7c427edc0)
![image](https://github.com/RiotGames/developer-relations/assets/48525283/a8664ac9-0148-49f7-aae3-c5bd21583358)

If I try to use that puuid, I'll get:
```json
{
    "status": {
        "message": "Bad request - PUUID was not in UUID format",
        "status_code": 400
    }
}
```

**Comment by f3ar161** [comment] 2024-01-16 20:48
Hey hi. Where are you trying to use this encrypted puuid?

**Comment by AoshiW** [comment] 2024-01-16 20:49
summoner-v4/GET_getByPUUID

**Comment by f3ar161** [comment] 2024-01-16 20:52
make sure you're using the same app here: 
<img width="319" alt="image" src="https://github.com/RiotGames/developer-relations/assets/14907413/cb6a73f1-3291-43ff-9dd8-7d5efe3ba959">
for me it worked with a puuid from the v4 service

**Comment by f3ar161** [comment] 2024-01-16 20:52
must be the same app in the 2 requests

**Comment by AoshiW** [comment] 2024-01-16 20:59
I know that.
if you look at the two pictures I sent, you will see that the `summonerId` is the same but the `puuid` is different
or try to use the `puuid` you get from `spectator-v4/GET_getCurrentGameInfoBySummoner`

**Comment by f3ar161** [comment] 2024-01-16 21:14
puuid encrypted value is different for two reasons: 

- Different Region selected.
- Different Application selected. 

Here's the response from spectator-v4: 

<img width="1054" alt="image" src="https://github.com/RiotGames/developer-relations/assets/14907413/90cca839-8b32-4515-a87c-cfeef0681e01">


here's the response from summoner-v4/GET_getByPUUID
I used the puuid from the spectator v4 and got the same encrypted puuid as a response as well.


<img width="1218" alt="image" src="https://github.com/RiotGames/developer-relations/assets/14907413/dd78537e-07f8-4dfe-a1aa-a4b34388035a">

both are correct. 
Please make sure the region and the application are the same in all the services that you are using.

**Comment by aPinat** [comment] 2024-01-16 21:51
I have the same issue on https://euw1.api.riotgames.com, PUUID from SpectatorV4 is way longer too, possibly double encrypted now?

**Comment by AoshiW** [comment] 2024-01-16 21:59
I don't know why but I only get this error when I test it on my active game in ARAM mode (other modes not tested)
if I use some id that I get with `spectator-v4/GET_getFeaturedGames` then everything works normally

**Comment by T3los** [comment] 2024-01-17 12:35
Problem is still here. Puuid in spectator by summ are not matching with the others queries (same region + same apitoken)

**Comment by TCM-dev** [comment] 2024-01-17 20:58
I can confirm the problem is still relevant right now, same region, same API token, but in spectator-v4, puuids are not returned with the same format as every single other routes, AFAIK puuid is always 78 characters long, not 134 all of sudden

<img width="1171" alt="image" src="https://github.com/RiotGames/developer-relations/assets/51787551/308909ba-8b4d-4d89-8ddd-aa9e285aaf04">
<img width="698" alt="image" src="https://github.com/RiotGames/developer-relations/assets/51787551/6d6e0946-3deb-422d-8156-7bf4b85c24ad">

**Comment by tisbells** [comment] 2024-01-17 21:10
Hey there, we're still looking into this and will provide an update as soon as we can

**Comment by aPinat** [comment] 2024-01-17 21:16
If it is any help, interestingly enough if it's a TFT match the PUUID is encrypted correctly, for all other LoL modes it is incorrect (what I'm assuming is just double encrypted).

**Comment by f3ar161** [comment] 2024-01-17 22:17
Hey all, the puuid is now fixed and working in all game modes.

**Comment by aPinat** [comment] 2024-01-17 22:18
Thank you, looks good to me!

**Closed** 2024-01-17 22:30 UTC
Labels: on hold: escalated to team, api: spectator-v4, scope: lol
