### ISSUE TITLE
[BUG] Invalid tournament codes

### ISSUE THREAD

**Issue by ZebraGemu** [RiotGames/developer-relations#457] opened 2021-02-22 18:03 UTC
**Bug Description**  
Tournament codes generated by the API are invalid. (EUW, BR1).

**Problem Description**  
After creating a tournament code (via code or using the Riot Website), the tournament code seems to be invalid.

**Expected Result**  
Expected to be able to join the tournament match using the created tournament code.

**Actual Result**  
Invalid code message
![image](https://user-images.githubusercontent.com/74376660/108749365-7fe33f00-751e-11eb-9802-2fadf6726a09.png)

**Developer Impact**  
I'm currently blocked by that bug because I'm trying to test automatic match validation using tournament codes, and I cannot play a tournament match.

* Frequency: Every API call.
* Severity: When it happens the whole tournament feature of my website stops working.
* Efficiency: Requires me to make 10x more API calls than necessary to compensate for the issue.
* User emails: I get frequent emails from users asking me about this issue.
* Etc

**Preconditions**  

* First condition
* Have a APP key so you're able to access the tournament API.

**Repro Steps**  

1. Access Riot API website
2. Try to create a tournament code using the API POST request
3. Try to enter the tournament match using the given tournament code

**Comment by RiotTuxedo** [comment] 2021-02-22 18:20
We're aware of this issue and are looking into it. As of right now, I've confirmed this issue affects all tournament providers in NA and EUW. If you're able to confirm it's also affecting other regions (this report mentions BR1), let me know. We're aware this issue has a wide impact and will be working to resolve this ASAP.

**Comment by ZebraGemu** [comment] 2021-02-22 18:23
Yes it's happening in other regions, at least here in BR1.

**Comment by Noobnoobwoduels** [comment] 2021-02-22 18:31
Hi, on EuNe too, since 22.00 GMT last night approximately. Affected 3 tournaments of mine. Thank you for adressing the issue and responding quickly !

**Comment by iDanielWongi** [comment] 2021-02-22 20:49
> We're aware of this issue and are looking into it. As of right now, I've confirmed this issue affects all tournament providers in NA and EUW. If you're able to confirm it's also affecting other regions (this report mentions BR1), let me know. We're aware this issue has a wide impact and will be working to resolve this ASAP.

now working for EUNE too.

**Comment by RiotTuxedo** [comment] 2021-02-23 00:44
At this time, we believe this issue should be resolved. If you continue to experience issues creating lobbies from tournament codes let us know. With there's no other comments in a week, we'll be closing this out.

**Closed** 2021-03-01 18:28 UTC
Labels: api: tournament-v4, closed: resolved, scope: lol, topic: underlying service, type: bug report
