### ISSUE TITLE
[BUG] [LOR] [404] Some recent matches (within 6 hours)

### ISSUE THREAD

**Issue by wangyi041228** [RiotGames/developer-relations#384] opened 2020-10-10 22:32 UTC
Some recent matches (within 6 hours) are 404 Data not found:

72966a27-2c3c-4970-954c-992c332e28fe
45feb5ee-d0e5-420b-b838-1e8a19dfc66c
ededae5e-8c7c-4d15-82df-c75aea991100

These matches belong to (NA) Galy#3614

Any solutions?

**Comment by RiotTuxedo** [comment] 2020-10-15 23:11
Duplicate of #381

**Closed by RiotTuxedo** 2020-10-15 23:11 UTC
