### ISSUE TITLE
Valorant Match API

### ISSUE THREAD

**Issue by Zohaib-Javed** [RiotGames/developer-relations#616] opened 2022-03-16 10:41 UTC
Do we have anything specific to match creation in VALORANT like we have tournament code in league of legend. Other than that, Can we get matchId directly without getting matchlists by puuid?

[/val/match/v1/matches/{matchId}]
[/val/match/v1/matchlists/by-puuid/{puuid}]

**Comment by raimannma** [comment] 2022-11-17 17:05
Duplicate of https://github.com/RiotGames/developer-relations/issues/262

**Comment by tisbells** [comment] 2023-12-27 01:24
Closing as this is covered under https://github.com/RiotGames/developer-relations/issues/262. We've let the game team know about this request and will update #216 if we get more info from them.

**Closed by tisbells** 2023-12-27 01:24 UTC
Labels: closed: duplicate, type: feature request, scope: val, api: val-match-v1
