### ISSUE TITLE
[FEATURE REQUEST] Need to return taglines from the lor-ranked leaderboard 

### ISSUE THREAD

**Issue by paaksing** [RiotGames/developer-relations#382] opened 2020-10-07 18:49 UTC
## Feature Request Description  
Taglines must be returned from the lor-ranked leaderboard in order to get their puuid, currently only some of them has the default tagline from lol. If PUUID can be returned instead, amazing.

## Expected Implementation
A consice and direct usage of the api that can be used together with the other apis.

## Actual Implementation  
Hyper hit or miss challenge is made instead

## Developer Impact
* More of a question: DO YOU WANT developers to mass 404 to your endpoints ?

## Player Impact
* Without effectively mapping the puuids, we can't provide matches to them, and they see nothing, and gives a "poor service" vote.

Thank you. This is well needed.

**Comment by RiotTuxedo** [comment] 2020-10-16 23:47
I asked the LOR team about this and they specifically want to leave the players in Master tier obscured. For now, I'm going to close this issue as working as intended, but feel free to open up another ticket in the future if things change over time and it feels like this decision is outdated.

**Closed by RiotTuxedo** 2020-10-16 23:47 UTC
