### ISSUE TITLE
v4/positions/by-summoner/ sometimes returning incorrect json response

### ISSUE THREAD

**Issue by danolanater** [RiotGames/developer-relations#76] opened 2019-01-29 17:47 UTC
Currently the summoner is in D1 and is still in series for master tier. Current series status is 2 wins 1 loss with 2 games left to play. Expected json response is this...
`[{"leagueId":"00000000-0000-0000-0000-000000000000","leagueName":"","queueType":"RANKED_SOLO_5x5","position":"APEX","tier":"DIAMOND","rank":"I","leaguePoints":100,"wins":34,"losses":28,"veteran":false,"inactive":false,"freshBlood":true,"hotStreak":false,"miniSeries":{"target":3,"wins":2,"losses":1,"progress":"WWLNN"},"summonerId":"A2ogLg0cGL_uxn7OWKbMC427I1rd0nxMf1Hd1j5pHfDOZfI","summonerName":"Sepeku AW"}]`

but maybe 50% of the time the api is returning this...
`[{"leagueId":"fcedb763-36b2-37b7-bd05-e2c032671290","leagueName":"Jarvan IV's Elementalists","queueType":"RANKED_SOLO_5x5","position":"NONE","tier":"MASTER","rank":"I","leaguePoints":85,"wins":34,"losses":28,"veteran":false,"inactive":false,"freshBlood":true,"hotStreak":false,"summonerId":"A2ogLg0cGL_uxn7OWKbMC427I1rd0nxMf1Hd1j5pHfDOZfI","summonerName":"Sepeku AW"}]`

here is the api call I am making
https://na1.api.riotgames.com/lol/league/v4/positions/by-summoner/A2ogLg0cGL_uxn7OWKbMC427I1rd0nxMf1Hd1j5pHfDOZfI?api_key=key

**Comment by RiotTuxedo** [comment] 2019-01-29 21:23
Duplicate of #70

**Closed by RiotTuxedo** 2019-01-29 21:23 UTC
