### ISSUE TITLE
Data dragon image quality

### ISSUE THREAD

**Issue by KonstantinosPetrakis** [RiotGames/developer-relations#725] opened 2023-01-11 08:05 UTC
Hello. 

After downloading and unpacking the tarball of data dragon the image quality (e.g of splash arts) is noticeably bad compared with the ones that are hosted online (in the data dragon API). Are they badly compressed, if so why?

Thanks!

**Comment by DarkIntaqt** [comment] 2023-01-13 19:55
That might be similar to #716

**Comment by KonstantinosPetrakis** [comment] 2023-01-13 20:03
Totally that! But not only loading screen assets but every single image that came into my attention. In order to get all the images in a decent quality one have to write a Python script and spam really bad that API.

**Comment by tisbells** [comment] 2023-12-27 03:16
Closing this out as it's a dupe of #716. Will note it's not just loading screen images and update in 716 if we get additional info.

**Closed by tisbells** 2023-12-27 03:16 UTC
Labels: closed: duplicate
