### ISSUE TITLE
[BUG] Third party verification is not working.

### ISSUE THREAD

**Issue by Bastianvgt** [RiotGames/developer-relations#315] opened 2020-06-06 22:24 UTC
**Bug Description**  
I try to verify accounts. The endpoint is responding 404.
This is not unusual, but I get multiple Reports for my verification Bot (Discord) since more than one week, and my testing results in the same.
So: Third Party Verification is not working.

**Problem Description**  
Third Party Verification is not working.

**Expected Result**  
200 and the Code instead of 404

**Actual Result**  
404, the API thinks I didnt send a Code

**Impact**

* Frequency: Every API call, I didnt get a right response since a week.
* Severity: When it happens, my Bot doesnt work.
* Cost: "Angry" users. They are not really angry, but look at "Efficiency".
* Efficiency: Someone has to verify themselves, I implemented this to reduce human work.
* User emails: I get frequent emails from users asking me why it doesnt work. We did an announcement that we will verify manualy, but thats not a good solution.
* Etc

**Preconditions**

* None. It doesnt work for anyone (as far as I know)

**Repro Steps**

1. Go to "Verification" in the Settings
1. Enter a code
1. Go to https://developer.riotgames.com/apis#third-party-code-v4 with the right summonerID
1. Get 404 ;-;

**Issue Comments**

Just tell me if this is a known issue. If yes:
1. For how long
1. When, and if you are going to fix it
1. Any workaround

If no:
1. Why this could be occuring for multiple people 😅

**Comment by thomasmarton** [comment] 2020-06-06 22:25
Duplicate of #289 
I'd like to ask you to close this one and keep track of the progress on the already existing issue

**Closed** 2020-06-06 22:32 UTC
