### ISSUE TITLE
[BUG] The Tournament API is not posting the match results to our callback endpoint.

### ISSUE THREAD

**Issue by sezeryesiltas** [RiotGames/developer-relations#772] opened 2023-05-25 19:20 UTC
**Bug Description**  
We have been using the "LOL TOURNAMENT-V4" APIs smoothly for a while now.

I had previously created a provider ID. We generate tournament codes for each event using the provider ID. The Tournament API would then post the match results to our callback endpoint after each match had ended and it was working well.

However today the Tournament API did not post any results for the created tournament codes. I checked the lobby events for the tournament codes and the event list data was empty in the result body.

Could you please check if the Tournament API is functioning as expected?

**Comment by Token07** [comment] 2023-05-26 00:30
Duplicate of #762

**Comment by tisbells** [comment] 2023-07-25 15:25
We expect this should be resolved by early August. Closing this out bc it's a dupe of https://github.com/RiotGames/developer-relations/issues/762. Will post updates in that ticket once we have them

**Closed by tisbells** 2023-07-25 15:25 UTC
