### ISSUE TITLE
League name and queuetype missing from League DTO

### ISSUE THREAD

**Issue by mccuts** [RiotGames/developer-relations#52] opened 2019-01-04 20:23 UTC
Good afternoon!

When a league is looked up via League ID (path: /lol/league/v4/leagues/{leagueId}) it is missing both the League's name and the queue type (solo, flex 5's, flex 3's). This issue is present in both v3 and v4. The documentation says this information should be provided. Is this a flaw within the documentation or is this a flaw within the API itself? I'll note this within my software when the answer is provided.

Thanks!

**Comment by jjmaldonis** [comment] 2019-01-08 04:13
This is a duplicate of Mingwei's comment here: https://github.com/RiotGames/developer-relations/issues/29#issuecomment-447608347

The other issue (#29) has a few things it mentions to fix, not just this.

**Closed** 2019-01-13 16:56 UTC
Labels: closed: duplicate, topic: riot games api
