### ISSUE TITLE
[BUG] Wrong image size

### ISSUE THREAD

**Issue by luizrossetti** [RiotGames/developer-relations#167] opened 2019-10-16 12:43 UTC
Leblanc R spell image is incorrectly sized in data dragon. Other images are 64x64 but only this is 800x800

**Comment by sousa-andre** [comment] 2019-10-16 13:05
Just check https://github.com/RiotGames/developer-relations/issues/101 👍

**Comment by RiotTuxedo** [comment] 2019-10-16 21:13
Closing this issue as it's a duplicate of #101. Please leave comments in that issue.

**Closed by RiotTuxedo** 2019-10-16 21:13 UTC
Labels: closed: duplicate, topic: data dragon, type: inconsistency
