### ISSUE TITLE
[BUG] MATCH-V5 APIs does not provide custom match information.

### ISSUE THREAD

**Issue by xoxodlf** [RiotGames/developer-relations#943] opened 2024-06-20 11:50 UTC
**Bug Description**  
The MATCH-V5 APIs of League of Legends do not provide custom match games.
**Problem Description**  
A clear and concise description of what the problem is.

**Expected Result**  
What were you expecting to happen after you performed the above steps? Include screenshots, logs, or a description.
Provide custom match information
**Actual Result**  
What actually happened after you performed the above steps? Include screenshots, logs, or a description.
404 error or don't provide
**Developer Impact**  
Describe how this affects you as a developer. Please include the frequency and severity of the issue.

* Frequency: Every API call.
* Severity: No way to get information

**Player Impact**  
Describe how this affects League of Legends players. Please include the frequency and severity of the issue.

**Comment by geozukunft** [comment] 2024-06-20 11:58
Duplicate of https://github.com/RiotGames/developer-relations/issues/472 this is not a BUG but rather an intentional descision from Riot that was made with the future possibility to get the data when having users authenticate which we are still waiting for. Duplicate non the less

**Comment by DarkIntaqt** [comment] 2024-06-20 11:59
Please check for similar issues before you open a new one, otherwise we would end in a flood of duplicate issues

**Closed** 2024-06-21 13:15 UTC
