### ISSUE TITLE
Hey, I fixed this issue for routing values in `OC1` and `SEA`.

### ISSUE THREAD

**Issue by WhoIsBest** [RiotGames/developer-relations#853] opened 2023-11-21 07:53 UTC
Hello 👋 Lucas,

Since, You’ve been resolved the route issues within OCE&SEA on 23,Aug this year successfully, it has been put on the back burner for a few months.

However, unfortunately the issue has been arisen in SEA sector from a few days again.

503 error occurring when invoked, sometimes, barely it has delivered a transaction of data.

P.S Could you fix this issue? As a Urgent 🚨 issue.

Best Regards, 
Many thanks 

© 2023 Who Is Best, Inc. 
https://best.ivunny.com

————————————————
              Hey, I fixed this issue for routing values in `OC1` and `SEA`.

If someone still receives a 503 error, please let me know.

_Originally posted by @lucasMesquitaBorges in https://github.com/RiotGames/developer-relations/issues/805#issuecomment-1689102081_

**Comment by bangingheads** [comment] 2023-11-21 07:55
Duplicate #849

**Comment by tisbells** [comment] 2023-11-21 13:08
Closing this dupe of https://github.com/RiotGames/developer-relations/issues/849

**Closed by tisbells** 2023-11-21 13:08 UTC
Labels: closed: duplicate
