### ISSUE TITLE
Match Timeline API Request shows 0 Ability Haste for all champions in match [BUG] 

### ISSUE THREAD

**Issue by mario-panzera** [RiotGames/developer-relations#715] opened 2022-12-11 19:35 UTC
**Bug/Problem Description**  
Two things, feels like they could be related; heartsteel's AH isn't reflected in the in-game stats, and a match timeline API request shows no AH for any champions in the match. I don't have much information regarding heartsteel (it was on Sett in an ARAM who I believe has a custom AH balance?) so I'll just cover the API issue.

**Expected Result**  
Champs in this match did build items that provide AH, as reflected in the post-game recap:
![image](https://user-images.githubusercontent.com/74384769/206924280-7a51b0fe-8151-4284-8eb1-062b7f8b9e35.png)
So, I'd expect the API request to show AH stats.

**Actual Result**  
Using the request URL https://americas.api.riotgames.com/lol/match/v5/matches/NA1_4514607517/timeline?api_key=RGAPI-02767a47-87f3-4c11-bbf7-a669b84b6fe8 every instance of "abilityHaste": returns as 0 (using ctrl+f). There was another report mentioning AP as well, but I do see that reflected properly (though I haven't checked every instance).

**Developer Impact**  
This doesn't effect me personally very much since I'm focusing on TFT but I noticed it and imagine it could cause issues for those who build for LoL.

* Frequency: Every API call.
* Severity: Only effects AH, as far as I can tell
* Cost: Free real estate
* Efficiency: No idea

**Player Impact**  
I imagine the heartsteel issue could cause confusion, though it seems to operate properly in-game (cooldowns are reduced, it just doesn't show the AH in the live stats). I don't know the use-cases for timeline API requests showing AH, so I can't speak to that.

**Preconditions**  
I've made the request a few times over the past two days and it's shown the same data each time.

**Repro Steps**  
Should be able to use the request URL above and see the same issue.

**Issue Comments**  
None really. Just noticed some data that wasn't showing correctly. Have fun.

**Comment by tisbells** [comment] 2023-07-31 14:10
Closing as this is a dupe of https://github.com/RiotGames/developer-relations/issues/711 and https://github.com/RiotGames/developer-relations/issues/411

**Closed by tisbells** 2023-07-31 14:10 UTC
