### ISSUE TITLE
[BUG] Champion Wukong's key on champions.json is called MonkeyKing

### ISSUE THREAD

**Issue by CyrilGrosjean** [RiotGames/developer-relations#551] opened 2021-09-28 09:16 UTC
**Problem Description**  
on http://ddragon.leagueoflegends.com/cdn/11.18.1/data/en_US/champion.json, every champions have their key named by their champion name except Wukong.

**Expected Result**  
In the json I send, it must be:  
`"Wukong":{"version":"11.18.1","id":"Wukong","key":"62","name":"Wukong","title":"the Monkey King","blurb":"Wukong is a vastayan trickster who uses his strength, agility, and intelligence to confuse his opponents and gain the upper hand. After finding a lifelong friend in the warrior known as Master Yi, Wukong became the last student of the ancient martial...","info":{"attack":8,"defense":5,"magic":2,"difficulty":3},"image":{"full":"Wukong.png","sprite":"champion2.png","group":"champion","x":288,"y":48,"w":48,"h":48},"tags":["Fighter","Tank"],"partype":"Mana","stats":{"hp":540,"hpperlevel":85,"mp":300,"mpperlevel":65,"movespeed":345,"armor":31,"armorperlevel":3.5,"spellblock":28,"spellblockperlevel":1.25,"attackrange":175,"hpregen":2.5,"hpregenperlevel":0.65,"mpregen":8,"mpregenperlevel":0.65,"crit":0,"critperlevel":0,"attackdamage":68,"attackdamageperlevel":3.5,"attackspeedperlevel":3,"attackspeed":0.711}}`

Name must be changed on:  
- Key
- ID
- Image, full

**Actual Result**  
`"MonkeyKing":{"version":"11.18.1","id":"MonkeyKing","key":"62","name":"Wukong","title":"the Monkey King","blurb":"Wukong is a vastayan trickster who uses his strength, agility, and intelligence to confuse his opponents and gain the upper hand. After finding a lifelong friend in the warrior known as Master Yi, Wukong became the last student of the ancient martial...","info":{"attack":8,"defense":5,"magic":2,"difficulty":3},"image":{"full":"MonkeyKing.png","sprite":"champion2.png","group":"champion","x":288,"y":48,"w":48,"h":48},"tags":["Fighter","Tank"],"partype":"Mana","stats":{"hp":540,"hpperlevel":85,"mp":300,"mpperlevel":65,"movespeed":345,"armor":31,"armorperlevel":3.5,"spellblock":28,"spellblockperlevel":1.25,"attackrange":175,"hpregen":2.5,"hpregenperlevel":0.65,"mpregen":8,"mpregenperlevel":0.65,"crit":0,"critperlevel":0,"attackdamage":68,"attackdamageperlevel":3.5,"attackspeedperlevel":3,"attackspeed":0.711}}` 

**Developer Impact**  
For my discord bot, my friends can't find Wukong because they don't understand why he's called MonkeyKing and not like every champions, by his champion name.

* Frequency: Every API call.  
* Severity: Small

**Comment by Token07** [comment] 2021-09-28 10:44
Duplicate of #7

**Closed** 2021-09-28 10:45 UTC

**Comment by MingweiSamuel** [comment] 2021-09-28 20:12
Right, in general the key seems to be the champion's `en_US` name but with spaces and punctuation removed and capitalization preserved. However there are the following exceptions:

`en_US` Name | Identifier | Id
---|---|---
"Cho'Gath" | "Chogath" | 31
"Fiddlesticks" | "FiddleSticks" | 9
"Kai'Sa" | "Kaisa" | 145
"Kha'Zix" | "Khazix" | 121
"LeBlanc" | "Leblanc" | 7
"Nunu & Willump" | "Nunu" | 20
"Vel'Koz" | "Velkoz" | 161
"Wukong" | "MonkeyKing" | 62

`KogMaw` and `RekSai` do have their second part capitalized, unlike the above.

List is from here: https://docs.rs/riven/2.0.0/riven/consts/struct.Champion.html#method.identifier
