### ISSUE TITLE
Match documentation is missing statPerk fields

### ISSUE THREAD

**Issue by JanOuborny** [RiotGames/developer-relations#128] opened 2019-05-15 22:30 UTC
The following fields are missing from the documentation of the `/lol/match/v4/matches/{matchId}` endpoint:

- `statPerk0`
- `statPerk1`
- `statPerk2`

**Comment by raitono** [comment] 2019-06-12 21:02
Duplicate of #98

**Comment by tisbells** [comment] 2023-07-25 21:17
Closing out old issues. Match-v4 is no longer supported. Feel free to reopen/comment if you feel this is in error.

**Closed by tisbells** 2023-07-25 21:17 UTC
Labels: pending: acknowledged, topic: documentation, type: inconsistency, api: match-v4
