### ISSUE TITLE
[BUG] [RSO] Refreshing tokens (grant_type=refresh_token) 100% returns empty 400

### ISSUE THREAD

**Issue by wktk** [RiotGames/developer-relations#673] opened 2022-08-19 02:00 UTC
**Bug Description** 

While the `grant_type=authorization_code` flow works, the `grant_type=refresh_token` flow is keeping returning a 400 error.

Endpoint: `POST https://auth.riotgames.com/token`

**Problem Description**

`grant_type=authorization_code` works.
```sh
$ curl https://auth.riotgames.com/token \
  -u "$RSO_CLIENT" \
  -d "grant_type=authorization_code&code=$RSO_CODE&redirect_uri=$RSO_REDIRECT_URI"
{"access_token":"eyJ6aXAiOi...URJg","refresh_token":"ap1:ODI1Mjc...HMg","scope":"openid offline_access","id_token":"eyJraWQ...jdAc","token_type":"Bearer","expires_in":3600}
```

But when it comes to the `refresh_token` flow, the endpoint returns a 400 error with an empty body even if you send valid parameters.

```sh
$ curl https://auth.riotgames.com/token \
  -D- -u "$RSO_CLIENT" \
  -d "grant_type=refresh_token&refresh_token=ap1:ODI1Mjc...HMg"
HTTP/2 400
date: Fri, 19 Aug 2022 01:36:11 GMT
content-type: application/json; charset=utf-8
content-length: 0
cache-control: no-store, no-cache, must-revalidate, proxy-revalidate
etag: W/"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk"
expires: 0
pragma: no-cache
surrogate-control: no-store
vary: Origin, Accept-Encoding
x-content-type-options: nosniff
x-download-options: noopen
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
x-riotgames-cdn: Cloudflare
set-cookie: __cf_bm=nIxKNvqbLsX0R_vijiuSUvGUb6_rhn4s40oCuKAfhfM-1660872971-0-ARrq/1y8iWNqLinIl7ebcknrCZQa59j5rmZBKhRGt+aSlnWwH3IyCjrqzCERAch4sG1jzlcykYa9lINnOarVUpI=; path=/; expires=Fri, 19-Aug-22 02:06:11 GMT; domain=.riotgames.com; HttpOnly; Secure; SameSite=None
server: cloudflare
cf-ray: 73cf28277b2aafc3-NRT

```

When I specify `grant_type=refresh_token`, it always returns an empty 400 response.  I guess there's something wrong with the implementation for `grant_type=refresh_token`.
```sh
$ curl https://auth.riotgames.com/token -u "$RSO_CLIENT" -d "grant_type=authorization_code"
{"error":"invalid_request","error_description":"Invalid request: Missing or empty code parameter"}
$ curl https://auth.riotgames.com/token -u "$RSO_CLIENT" -d "grant_type=foo"
{"error":"unsupported_grant_type"}
$ curl https://auth.riotgames.com/token -u "$RSO_CLIENT" -d "grant_type=refresh_token"
```

**Expected Result**  
Returns a refreshed token or error description in JSON

**Actual Result**  
Returns an empty 400 response

**Developer Impact**  

* Frequency: Every API call

**Player Impact**  

**Preconditions**  

**Repro Steps**  
As described above

**Issue Comments**

**Comment by lucasMesquitaBorges** [comment] 2022-08-22 21:06
Hey @wktk
It's not a bug. The refresh token flow isn't enabled for third party clients.

I'll close the issue. If you need more context feel free to re-open.

**Closed by lucasMesquitaBorges** 2022-08-22 21:06 UTC

**Comment by thomasmarton** [comment] 2022-08-22 21:31
@lucasMesquitaBorges while not the original poster, I'd appreciate some context behind the decision.

What exactly is the issue with third party clients having access to the refresh token flow? (especially since we do get refresh tokens from RSO)

**Comment by wktk** [comment] 2022-08-29 08:25
Hi @lucasMesquitaBorges, thank you for the response!

That sounds a little bit strange to me as

- Using refresh tokens is documented in the tutorial called `Implementing Riot Sign On`, which I received when I was granted access to RSO
- My RSO client comes with an `offline_access` scope, and users authorize `Offline Access` to us, which may mean the client can refresh its authorization
- Refresh tokens are included in `authorization_code` responses

In my use case, refreshing tokens is helpful because I need to keep the Riot IDs of my users up to date.  Is there any chance to get token refreshing enabled for third parties?

(and it seems like I don't have permission to re-open an issue)

**Comment by dvf** [comment] 2023-03-09 19:06
Hey @lucasMesquitaBorges 

Just to echo what the others have said. Keeping tokens up to date is an important security measure because it allows us to know when someone has revoked our access (as well as keeping someone's user details up to date).

Is there any more information here?

**Comment by lucasMesquitaBorges** [comment] 2023-08-08 19:31
Sorry for the late reply on this. Some decisions were made that changed our view for `refresh_token` flow.

New rsoclients requested at [beta.developer.riotgames.com](beta.developer.riotgames.com) will contain by default the `refresh_token` grant type.

To request for an existing rsoclient send an email to devrel-rg@riotgames.com
