### ISSUE TITLE
[BUG] Match-V5 data is not updated

### ISSUE THREAD

**Issue by kwangyeonJJANG** [RiotGames/developer-relations#646] opened 2022-06-07 04:43 UTC
**Bug Description**  
I am not getting data on matches played after May 31th from API:
MATCH-V5
endpoint: /lol/match/v5/matches/by-puuid/{puuid}/ids

**Expected Result**  
I am getting up-to-date data on the matches played

**Actual Result**  
I am not getting up-to-date data on the matches played

**Developer Impact**  
The platform that I develop is based on data about historical matches so this is a critical issue for me

* Frequency: Every API call.

**Preconditions**  
No conditions must be met in order for this bug to occur

**Comment by gameboyring** [comment] 2022-06-07 10:53
me too,please fix it.
the bug is not for all summoners and all developers

**Comment by geozukunft** [comment] 2022-06-07 11:40
Please see #644 for this

**Comment by junga12** [comment] 2022-08-14 20:53
I have a same issue. 
some PUUID cannot get game history.

**Comment by tisbells** [comment] 2023-08-02 19:31
Dupe of https://github.com/RiotGames/developer-relations/issues/644, which was resolved. Closing this out, feel free to reply if you are still having issues

**Closed by tisbells** 2023-08-02 19:31 UTC
