### ISSUE TITLE
[BUG] Riot Champion Spell Info issue

### ISSUE THREAD

**Issue by Meerkat1030** [RiotGames/developer-relations#862] opened 2023-12-13 07:45 UTC
I was call API Data Dragon Data & Asset 
but I can't check the AD or AP coefficient of the skill

![1](https://github.com/RiotGames/developer-relations/assets/45195374/eb4d3e06-a578-417b-9a80-e666ea431ccb)

How can I check the coefficient

**Comment by Querijn** [comment] 2023-12-13 07:50
Hey! This is a duplicate of https://github.com/RiotGames/developer-relations/issues/672

Also, since DDragon is no longer actively developed, there's a good chance this won't get fixed. 

I recommend https://github.com/meraki-analytics/lolstaticdata

**Comment by tisbells** [comment] 2023-12-22 19:25
Closing as this is a duplicate. Confirming we unfortunately don't expect this to be fixed, but we will still pass it along and update #672 if changes are made.

**Closed by tisbells** 2023-12-22 19:25 UTC
Labels: closed: duplicate, topic: ddrag lol
