### ISSUE TITLE
[BUG] geting TFT Double Up Rank in league-v4 api response

### ISSUE THREAD

**Issue by 27tj** [RiotGames/developer-relations#745] opened 2023-02-22 19:47 UTC
**Bug Description**  
 geting TFT Double Up Rank in league-v4 api response

**Problem Description**  
using GET /lol/league/v4/entries/by-summoner/{encryptedSummonerId}] will get TFT Double Up Rank

**Expected Result**  
 [{
    leagueId: 'fcc6445a-78ca-49c2-b420-4f85d0820903',
    queueType: 'RANKED_SOLO_5x5',
    tier: 'PLATINUM',
    rank: 'IV',
    summonerId: 'THhJzmHBFyrNvzUYS8DP_txnEZRdIMYxJHTFkMtvPhpHjtcnVSOWkAS32A',
    summonerName: 'SERGEI PAVLOVICH',
    leaguePoints: 68,
    wins: 67,
    losses: 61,
    veteran: false,
    inactive: false,
    freshBlood: false,
    hotStreak: false
  },
  {
    leagueId: '6a7e6bbc-86b6-4ca5-8f0a-bbdb6486e1f4',
    queueType: 'RANKED_FLEX_SR',
    tier: 'DIAMOND',
    rank: 'IV',
    summonerId: 'THhJzmHBFyrNvzUYS8DP_txnEZRdIMYxJHTFkMtvPhpHjtcnVSOWkAS32A',
    summonerName: 'SERGEI PAVLOVICH',
    leaguePoints: 0,
    wins: 53,
    losses: 61,
    veteran: false,
    inactive: false,
    freshBlood: false,
    hotStreak: false
  }
]

**Actual Result**  
[
  {
    leagueId: '16393aa7-7e81-4342-b7c8-8d9c96cc1c92',
    queueType: 'RANKED_TFT_DOUBLE_UP',
    tier: 'PLATINUM',
    rank: 'IV',
    summonerId: 'THhJzmHBFyrNvzUYS8DP_txnEZRdIMYxJHTFkMtvPhpHjtcnVSOWkAS32A',
    summonerName: 'SERGEI PAVLOVICH',
    leaguePoints: 0,
    wins: 27,
    losses: 19,
    veteran: false,
    inactive: false,
    freshBlood: false,
    hotStreak: false
  },
  {
    leagueId: 'fcc6445a-78ca-49c2-b420-4f85d0820903',
    queueType: 'RANKED_SOLO_5x5',
    tier: 'PLATINUM',
    rank: 'IV',
    summonerId: 'THhJzmHBFyrNvzUYS8DP_txnEZRdIMYxJHTFkMtvPhpHjtcnVSOWkAS32A',
    summonerName: 'SERGEI PAVLOVICH',
    leaguePoints: 68,
    wins: 67,
    losses: 61,
    veteran: false,
    inactive: false,
    freshBlood: false,
    hotStreak: false
  },
  {
    leagueId: '6a7e6bbc-86b6-4ca5-8f0a-bbdb6486e1f4',
    queueType: 'RANKED_FLEX_SR',
    tier: 'DIAMOND',
    rank: 'IV',
    summonerId: 'THhJzmHBFyrNvzUYS8DP_txnEZRdIMYxJHTFkMtvPhpHjtcnVSOWkAS32A',
    summonerName: 'SERGEI PAVLOVICH',
    leaguePoints: 0,
    wins: 53,
    losses: 61,
    veteran: false,
    inactive: false,
    freshBlood: false,
    hotStreak: false
  }
]

**Developer Impact**  

Frequency: Every API call. 
Severity: Just annoying.

**Comment by bangingheads** [comment] 2023-02-22 19:48
Duplicate #572

**Comment by geozukunft** [comment] 2023-02-22 19:48
Duplicate of #572

**Comment by tisbells** [comment] 2023-07-26 15:34
Closing, dupe of https://github.com/RiotGames/developer-relations/issues/572

**Closed by tisbells** 2023-07-26 15:34 UTC
Labels: closed: duplicate
