### ISSUE TITLE
[BUG] Valorant Console Match List Endpoint Always Returns Error for AP Region

### ISSUE THREAD

**Issue by serkanbal** [RiotGames/developer-relations#963] opened 2024-07-25 11:36 UTC
**Bug Description**  
Valorant console match list endpoint always returns error for AP region.

**Problem Description**  
When the `/val/match/console/v1/matchlists/by-puuid/{puuid}` endpoint is executed against any valid puuid for the `AP` region, the response is always `error: Bad Request`. This is the response I get when I call the endpoint at `developer.riotgames.com`.
When I call the endpoint from my backend, the whole error response is:
```
{
  "status": {
    "message": "Bad request - Invalid routing value ap",
    "status_code": 400
  }
}
```

**Expected Result**  
We expect the response to include the match list of console players populated with match ids.

**Actual Result**  
The endpoint response is always `error: Bad Request`.

**Developer Impact**  
Player satisfaction drops in the AP region. This negatively affects our app's ratings.

* Frequency: Every API call.
* Severity: High. Console players in AP region are unable to use our app.
* User complaints: We get complaints on our Discord channel.

**Player Impact**  
Console players in AP region are unable to use our app.

* Frequency: Every time the user launches the app.
* Severity: High. Console players in AP region are unable to use our app.
* Quantity: All AP console users.
* Region: AP.

**Repro Steps**  

1. Log in to developer.riotgames.com
1. First select `APIS` then the `VAL-CONSOLE-MATCH-V1` cluster and finally `/val/match/console/v1/matchlists/by-puuid/{puuid}`
1. Enter a valid `puuid` for `AP` region, select the correct `platformType` and execute against AP region.

**Comment by PenguinDevs** [comment] 2024-07-29 05:43
I can confirm that this is occurring among my users too, and always have been since the Valorant console endpoints were introduced.

**Comment by tisbells** [comment] 2024-08-02 15:13
Hi, we're looking into this.

**Comment by tisbells** [comment] 2024-08-06 21:04
Hey there, this should be fixed. Please let us know if not.

**Closed** 2024-08-06 21:05 UTC
Labels: type: bug report, on hold: escalated to team, scope: val, api: val-console-match-v1
