### ISSUE TITLE
[BUG] Match-V5 API Returns Stat Perk IDs Instead of Secondary Rune IDs After Patch 14.24

### ISSUE THREAD

**Issue by alholm** [RiotGames/developer-relations#1018] opened 2024-12-11 12:20 UTC
**Bug Description**  
Match V5 API is returning incorrect perk IDs in the secondary runes section, showing stat perk IDs (5000+) instead of secondary rune IDs (8000+).

**Problem Description**  
In the match data JSON, the path `/match/info/participants/../perks/styles/1/selections` contains stat perk IDs where secondary rune IDs should be. This started occurring after patch 14.24.

**Expected Result**  
Secondary runes section should contain valid secondary rune IDs (8000+ range):
```json
{
  "description": "subStyle",
  "selections": [
    {
      "perk": 8473,
      "var1": 2278
    },
    {
      "perk": 8242,
      "var1": 150
    }
  ],
  "style": 8400
}
```

**Actual Result**  
The API returns stat perk IDs (5000+ range):
```json
{
  "description": "subStyle",
  "selections": [
    {
      "perk": 5007,
      "var1": 0,
      "var2": 0,
      "var3": 0
    },
    {
      "perk": 5001,
      "var1": 0,
      "var2": 0,
      "var3": 0
    }
  ],
  "style": 8000
}
```

**Developer Impact**  
* Frequency: Every Match V5 API call since patch 14.24
* Severity: Applications incorrectly display rune information or crash when trying to map rune IDs to actual runes
* Efficiency: Requires additional logic to handle incorrect data format or filter out invalid responses
* User Experience: Displays wrong rune builds to users, affecting build analysis and statistics

**Preconditions**  
* Using Match V5 API: [/lol/match/v5/matches/{matchId}](https://developer.riotgames.com/apis#match-v5/GET_getMatch)

**Repro Steps**  
1. Call Match V5 API (example match ID: KR_7411069617)
2. Parse the JSON response
3. Navigate to perks/styles/1/selections in the response
4. Observe incorrect perk IDs in 5000+ range

**Comment by bangingheads** [comment] 2024-12-11 14:10
Duplicate of #947

**Comment by alholm** [comment] 2024-12-11 14:21
well yes, same symptoms but in patch 14.24 it became reproducible every match.

**Comment by colin-j-rm** [comment] 2024-12-12 05:12
Having the same issue, can't track secondary rune stats with this, all stat sites have missing data (check u.gg, lolalytics, mobalytics, onetricks.gg etc). 100% of patch 14.24 matches have incorrect data for secondary runes.

**Comment by WhoIsBest** [comment] 2024-12-12 09:27
FYI,

Hello, there!

**1. API for a current game is providing with correct data of secondary runes. (though 14.24 ver.)**

   [**spectator-v5**] : to Get Current Game information, [/lol/spectator/v5/active-games/by-summoner/{encryptedPUUID}]

* Captured in json (Current Game)
-----------------------------------------------------------------------------------
gameId: 5179886310

 
  perkIds: [8369, 8321, 8313, 8316, **_9111_,** **_9105_,** **5007**, 5008, **5001**], perkStyle: 8300, perkSubStyle: 8000


-----------------------------------------------------------------------------------



**2. API for a match is providing with incorrect data replaced by flex&offense of statPerks.**
   
   [**match-v5**]  : to Get Match information, [/lol/match/v5/matches/{matchId}]

* Captured in json (Completed Game)
-----------------------------------------------------------------------------------
matchId: NA1_5179886310
statPerks: {defense: 5008, flex: **5001**, offense: **5007**},


  description: primaryStyle,
    perk: 8369, var1: 908,..,
    perk: 8321, var1: 525,..,
    perk: 8313, var1: 3,..,
    perk: 8316, var1: 5,..
 style: 8300

  description: **subStyle**,
    perk: **5007**, var1: 0,..    <--  **_9111_** (offense: **5007** instead)
    perk: **5001**, var1: 0,..    <--  **_9105_** (flex: **5001** instead)
 style: 8000
 
-----------------------------------------------------------------------------------



P.S ASAP Escalate to, please. (In our case, Impacted on front UI)



-----------------------------------------------------------------------------------
Best Regards,

https://best.ivunny.com

© Who Is Best, Inc. 
-----------------------------------------------------------------------------------

**Comment by 1337MARCEL** [comment] 2024-12-14 02:25
I think this issue was fixed w/ the game update (`14.24.643.5128`) that was released 8 hours ago.

**Comment by WhoIsBest** [comment] 2024-12-14 05:31
> I think this issue was fixed w/ the game update (`14.24.643.5128`) that was released 8 hours ago.


Hello, 1337Marcell, it was stabilized rapidly. Thanks for your effort!

Many Thanks,
Best regards

https://best.ivunny.com/

© Who Is Best, Inc.

**Comment by lucasMesquitaBorges** [comment] 2024-12-17 17:38
Thank you all for reporting this issue.  A fix was released last Friday as @1337MARCEL reported.

**Closed as completed by lucasMesquitaBorges** 2024-12-17 17:38 UTC
Labels: type: bug report, closed: resolved, api: match-v5

**Comment by WhoIsBest** [comment] 2024-12-17 21:02
Thank you,
@lucasMesquitaBorges 


Best Respectfully regards

https://best.ivunny.com/

© Who Is Best, Inc.
