### ISSUE TITLE
[BUG] Image in pack (Samira)

### ISSUE THREAD

**Issue by d-osuch** [RiotGames/developer-relations#439] opened 2021-01-24 11:01 UTC
**Bug Description**  
Bug image in assets from Developer Portal

**Problem Description**  
I downloaded packs from developer portal and Samira image was bad for assets. Samira had Sett image.

**Expected Result**  
Can you fix it?

**Comment by GetPastTheMonkey** [comment] 2021-01-24 12:11
Duplicate of #372 

Additionally, @bangingheads is keeping a list of incorrect DDragon images in #348

**Comment by tisbells** [comment] 2023-07-25 21:45
Closing old issues; resolved

**Closed by tisbells** 2023-07-25 21:45 UTC
