### ISSUE TITLE
[BUG] TFT Match-v1 API returns no traits for latest patch

### ISSUE THREAD

**Issue by SamGuthrie** [RiotGames/developer-relations#330] opened 2020-07-08 10:37 UTC
**Bug Description**  
TFT-Match-v1 API only returns traits for the player in first place. Others are empty

**Developer Impact**
* Frequency: Every API call..
* Severity: I cannot update my website

**Player Impact**
* Frequency: Every time the user visits the site, they experience this issue.
* Severity: Cannot get up to date data from the latest patch
* Quantity: This affects all player's TFT match history
* Region: This affects all regions.

**Preconditions**
* Play a game of TFT on 10.14

**Repro Steps**
1. query games from the latest patch, example:
https://europe.api.riotgames.com/tft/match/v1/matches/EUW1_4697283425

**Comment by whyando** [comment] 2020-07-08 11:59
I can confirm I've seen this missing data on recent tft games.
Severity: High
Impact: High

**Comment by JamesYouL2** [comment] 2020-07-08 12:49
The same is true for items. Only the winning player has items. Items are empty for all other players.

**Comment by MMA15** [comment] 2020-07-08 19:04
I am running into the same issue. It is really affecting our site.
Severity: High
Impact: High

**Comment by RiotTuxedo** [comment] 2020-07-09 20:09
We're looking into this.

**Comment by Patyfatycake** [comment] 2020-07-17 05:20
Not trying to sound pushy or anything, but has there been any update on the status of this? Since its kind of one the main features I assume people would use the API for.

**Comment by shosenfeld** [comment] 2020-07-19 16:36
Faced the same problem in my project. 
Seems like you took out the "style"-property on the trait-class, maybe this gives a hint

**Comment by GaggingQueen** [comment] 2020-07-21 15:13
Hi! i am supporting TFTactics overwolf app as a big personal fan, and i really think its a shame their enormous work about match history and statistics is not able to provide statistics to the users because of this bug.  
I'm sure its a straight forward thing to correct. 

A little life advice... All the things you could complete in 10 minutes or less, just do them now, instead of waste time and energy planning when you will do it :)  its not a 2 week task. 
I used stupid amount of money on skins and little legends, so i am in position to tell you that this is unacceptable. The bug in the first place is unacceptable. You not fixing it in a fair time, is beyond unacceptable.

Yes you lazy pizza eating riot developer, YOU! fix it. NOT tomorrow. NOW. seriously, its propably just an array you need to expand from 1 to 8.

Last year i used 6,354 dollars on LOL content.  I'm paying half your sallary! go fix the bug!

**Comment by RiotTuxedo** [comment] 2020-07-21 20:09
Patch 10.15 is rolling out which should have a fix for this issue. OCE is on patch 10.15, but I still have to confirm the issue is resolved.

You can see the issue being referenced in the patch notes for 10.15 under bugfixes.
https://na.leagueoflegends.com/en-us/news/game-updates/teamfight-tactics-patch-10-15-notes/

**Comment by Patyfatycake** [comment] 2020-07-21 22:44
Can confirm fixed on KR/OCE

`{"placement":7,"level":8,"last_round":26,"time_eliminated":1419.4124755859375,"companion":{"skin_ID":10,"content_ID":"c44b7607-a556-40d2-9433-cc5d239526f8","species":"PetTurtle"},"traits":[{"tier_total":4,"Style":2,"Name":"DarkStar","tier_current":2,"num_units":4},{"tier_total":3,"Style":1,"Name":"Infiltrator","tier_current":1,"num_units":2},{"tier_total":1,"Style":0,"Name":"MechPilot","tier_current":0,"num_units":1},{"tier_total":3,"Style":1,"Name":"Protector","tier_current":1,"num_units":2},{"tier_total":3,"Style":1,"Name":"Set3_Celestial","tier_current":1,"num_units":2},{"tier_total":2,"Style":1,"Name":"Set3_Mystic","tier_current":1,"num_units":2},{"tier_total":2,"Style":1,"Name":"Sniper","tier_current":1,"num_units":2},{"tier_total":3,"Style":0,"Name":"StarGuardian","tier_current":0,"num_units":1}]`

`{"tier":2,"items":[19,15,49],"character_id":"TFT3_Jhin","name":"","rarity":3},`

**Comment by JamesYouL2** [comment] 2020-07-21 23:53
Yup, looks fixed on OCE too. Weird bug. Sorry for the frustration, wow @GaggingQueen...

**Comment by GaggingQueen** [comment] 2020-07-22 09:19
hi developers, Im sorry about my attitude yesterday.  i was suffering from a manic episode resulting in incontrollable childlike behavior. I wish i had expressed myself in a more respectful manner. anyways, i got my point across.

**Comment by Patyfatycake** [comment] 2020-07-22 11:53
> 
> 
> hi developers, Im sorry about my attitude yesterday. i was suffering from a manic episode resulting in incontrollable childlike behavior. I wish i had expressed myself in a more respectful manner. anyways, i got my point across.

Yeah you could have come across better. I'm sure people respect you for apologizing, very rare nowadays online. Lets just move on and be better.

**Comment by tisbells** [comment] 2023-07-25 21:51
Closing old issues; this was resolved

**Closed by tisbells** 2023-07-25 21:51 UTC
Labels: on hold: escalated to team, api: tft-match-v1
