### ISSUE TITLE
[FEATURE REQUEST] Adding DRAGON/BARON events

### ISSUE THREAD

**Issue by ANN0Y1NGHACKER** [RiotGames/developer-relations#388] opened 2020-10-14 19:09 UTC
Hi,

I was using the **Live Client API** and found that the `/liveclientdata/eventdata` does not return Dragon Kill or Barron Kill but returns all other info. I would really like if you guys add this feature.

Thank You

**Comment by bangingheads** [comment] 2020-10-14 19:26
Duplicate of #236

**Comment by RiotTuxedo** [comment] 2020-10-16 23:41
As @bangingheads mentioned, this is a duplicate of another request. Going to close this out, but we'll keep it in mind for future changes to the live client data API.

**Closed by RiotTuxedo** 2020-10-16 23:41 UTC
Labels: closed: duplicate

**Comment by diOnysosdk** [comment] 2022-12-29 04:32
So where are we on that?

Im just an indie dev. who don't think i can get the full live match api from you guys, so i make my overlays with your data from live client, and i think a lot of us would appreciate getting baron/dragons in events.
