### ISSUE TITLE
[BUG][TOURNAMENT-V4] After LOL matches, we will not be called back to the endpoint.

### ISSUE THREAD

**Issue by szunyogh** [RiotGames/developer-relations#789] opened 2023-07-19 13:08 UTC
No callbacks are made to the specified endpoint at the provider (/lol/tournament/v4/providers).
The data retrieved at the endpoint "/lol/tournament/v4/lobby-events/by-code/{tournamentCode}" is also empty after the match.

I found several announcements about this here, but I didn't see an answer anywhere. I have written to the support on the dev page for several weeks, but there is no answer. It's all a mess, can someone really help me, I'm going crazy that no one can do anything. This is why the development and the release of the product are delayed, because everyone at Riot Games is lazy.

**Comment by Token07** [comment] 2023-07-19 13:24
Duplicate of #762

**Comment by szunyogh** [comment] 2023-07-19 13:27
@Token07  I saw that my question is similar to the one you marked, but there is no answer there either. And I want an answer.

**Comment by Token07** [comment] 2023-07-19 13:28
Unfortunately there is no solution. There hasn't been any visible effort to resolve the callback issue.

**Comment by szunyogh** [comment] 2023-07-19 13:31
@Token07 When is it expected, or is there anything nominal in sight?

**Comment by geozukunft** [comment] 2023-07-19 13:33
There is no answer expected. The API has been having problems for many months. Looking at the TOURNAMENT-STUB it has been non functional since November 2022 and the fact that is not working hasn't even been acknowledged by Riot. I wouldn't get my hopes high of this getting fixed any time soon. It is probably more likely that the tournament APIs as they exist right now will rather be retired than fixed.

**Comment by Token07** [comment] 2023-07-19 13:35
Riot has pretty much dropped the ball on comms with the developer community outside of app approval/rejections. Any sort of response or acknowledgement at this point should be considered unusual and unexpected.

**Comment by szunyogh** [comment] 2023-07-19 13:37
Wunderbar

**Comment by tisbells** [comment] 2023-07-24 21:46
No exact timeline unfortunately, but we expect this should be resolved by early August.

**Comment by tisbells** [comment] 2023-07-25 15:23
Closing bc dupe of https://github.com/RiotGames/developer-relations/issues/762

**Closed** 2023-07-25 15:23 UTC

**Comment by nexusacademypro** [comment] 2023-08-01 20:57
If just query the player using match-v5 and filter for type TOURNEY and then check the tournament-id as part of the matches response. Could that be how it works?
