### ISSUE TITLE
API summoner id

### ISSUE THREAD

**Issue by ZezoCraft** [RiotGames/developer-relations#148] opened 2019-08-04 08:13 UTC
**Describe the bug**  
when i fetch **https://eun1.api.riotgames.com/lol/summoner/v4/summoners/by-name/Ameerjoker**
using **https://developer.riotgames.com/api-methods/#summoner-v4**
i get the right id of the user
but when i use it via API i get different id that's not working with League V4 

**Issue Description**  
nothing to say here

**Expected Result**  
it was working in the past it also working now but not League v4

**Actual Result**  
i get error { status: { message: 'Forbidden', status_code: 403 } }

**Comment by ZezoCraft** [comment] 2019-08-04 08:14
i mean ID and AccountID

**Comment by Querijn** [comment] 2019-08-04 08:43
This is not a bug.

Common Reasons:
No API key was provided with the API request
An invalid API key was provided with the API request
A blacklisted API key was provided with the API request
The API request was for an incorrect or unsupported path

https://developer.riotgames.com/response-codes.html

**Comment by MingweiSamuel** [comment] 2019-08-05 04:20
This is probably because the IDs are encrypted per project. You will get different (encrypted) IDs when you use your development key from when you use your project key. The IDs you get are not interchangeable

**Comment by stelar7** [comment] 2019-08-16 11:55
can be closed as issue is related to the v3->v4 change, and not a general api issue @RiotTuxedo

**Closed** 2019-08-16 18:37 UTC
