### ISSUE TITLE
"/lol/match/v4/matchlists/" It's better contain game result (win/lose)

### ISSUE THREAD

**Issue by qthekan** [RiotGames/developer-relations#329] opened 2020-07-06 08:02 UTC
Because the winning rate per champion or winning rate per line can be developed with just one call of API.
The current version is too inefficient.

for example,
If the player has played 100 games, "/lol/match/v4/matches/{matchId}" must be called 100 times for winning rate...

**Comment by Token07** [comment] 2020-07-06 14:05
Duplicate of #86

**Comment by tisbells** [comment] 2023-07-25 21:36
Closing out old issues. Match-v4 is no longer supported, feel free to re-open or comment if you feel this is in error.

**Closed by tisbells** 2023-07-25 21:36 UTC
