### ISSUE TITLE
[BUG] Samira's tiles are incorrect

### ISSUE THREAD

**Issue by itachi42** [RiotGames/developer-relations#406] opened 2020-11-03 11:22 UTC
**Bug Description**
Samira's tiles are incorrect.

**Problem Description**
Both of Samira's tiles are in fact Sett tiles.

https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_0.jpg
https://ddragon.leagueoflegends.com/cdn/img/champion/tiles/Samira_1.jpg

**Expected Result**
The links and the tarball should show the simira's tiles

**Actual Result**
The actual result are Sett's tiles

**Comment by bangingheads** [comment] 2020-11-03 17:03
This is a duplicate of #372 

I am keeping a list of incorrect images in DDragon on issue #348

**Closed** 2020-11-04 08:03 UTC
Labels: closed: duplicate

**Comment by itachi42** [comment] 2020-11-04 08:59
Ok sorry i didn't see that other ticket regarding Samira.
Although aren't we supposed to follow guidelines for issues ?
At least my ticket was kinda complete :smile:
