### ISSUE TITLE
[BUG][TFT] Match missing from match history

### ISSUE THREAD

**Issue by HeuHax** [RiotGames/developer-relations#462] opened 2021-03-08 16:16 UTC
This problem occurs both in game and in the API. I'll refer mostly to the API as that is where I get the data from.
I'll use myself as an example, but I have other examples from other users as well where this has occurred.
My summoner name is "Heumusen" and it's on "EUW1"

When I call the match list endpoint I get this result:
`[
    "EUW1_5135792173",
    "EUW1_5134896854",
    "EUW1_5134514224",
    "EUW1_5133882598",
    "EUW1_5131837603",
    etc.`

Between the two first id's is actually missing this id: EUW1_5135704004.

I actually only found the id because I was playing with some friends where the id weren't missing.

This makes no sense to me, so it must surely be a bug.

Hoping for a fix - Cheers.

**Comment by RiotTuxedo** [comment] 2021-03-11 23:25
@HeuHax we've seen a couple rare cases where match ids aren't properly included in a timeline for specific players. There's some work already in progress to make this process more robust and make these exceptions less likely.

**Comment by cauchy2384** [comment] 2021-04-30 08:08
Up. This happens a lot for players with set5 release.

**Comment by RiotTuxedo** [comment] 2021-05-01 03:25
I'll follow up with the team on this. We're generally aware and working to make match-v5 more robust, but if you have examples it would help demonstrate how frequently this bug occurs.

**Comment by cauchy2384** [comment] 2021-05-01 06:20
I think that this bug could be narrowed to euw summoners. 
Recent examples are:
- EUW "TL AKAWonder", latest match in list is EUW1_5170868184, March 24
- EUW "TL Snoodyboo", latest match in list is EUW1_5203169026, April 10

**Comment by RiotTuxedo** [comment] 2021-05-01 08:16
@cauchy2384 I've updated my original comment. The missing match and the player it's missing is what we'd be looking for.

**Comment by cauchy2384** [comment] 2021-05-01 08:21
@RiotTuxedo I would say all matches since march 24 for EUW "TL AKAWonder". I don't know the exact ids, since I can't get them via Riot API. But there are lots of matches for this concrete player at the lolchess: https://lolchess.gg/profile/euw/tlakawonder

**Comment by cauchy2384** [comment] 2021-05-01 16:02
An update.
I've examined profiles of players who played games with EUW "TL AKAWonder". There were some matches that he has participated in, but which are not shown in his match list. Missing matches that I've found: 
5237155646, 5237272563,5237250113, 5237337709, 5237475243, 5237554340, 5237781004, 5237834021, 5239189705, 5239227021, 5239467218, 5239860904, 5239904469.
All of them are for patch 11.9.

**Comment by trebonius0** [comment] 2021-05-02 17:16
I've  reports from players for this also

The TFT matchlist for this player (encryptedPuuid: Q0qWOJ804ogn_TWyb2WYmF9iSJn_Jqb65WS4xOcosHCwut5xz4vvrd_LEG1wg36yTTJcGytp5Cf8fQ - region: EUNE) is outdated
The last known  TFT match in it is match: EUN1_2817726625
Nevertheless he played match EUN1_2820517963 (which doesn't appear in his tft matchlist)

Thanks

**Comment by wdprez** [comment] 2021-05-03 21:40
My (TheWehT) tft match history in-game shows that my last match is from 1/5, while I played matches both today (3/5) and yesterday (2/5).
Lolchess shows more matches, but also not all of the matches I played: https://lolchess.gg/profile/euw/theweht/s5/matches
My 'tier graph' in the lolchess overview is correct, but does not correspond to the ranked matches that are showing in the match history because matches are missing.
I don't know how to get the missing match ID's, so maybe my info isn't really useful.

**Comment by RiotTuxedo** [comment] 2021-05-04 21:25
Hey all, thanks for the reports. We believe this was due to a cache invalidation issue and that no data was lost. These player's matchlists should be updated after they play their next game. Will close this out in a week if there are no further issues.

**Comment by wdprez** [comment] 2021-05-04 21:54
Yes my match history is back to normal now!

**Closed** 2021-05-17 18:34 UTC
Labels: api: match-v5, pending: acknowledged, scope: lol, topic: underlying service, type: bug report

**Comment by Deftcorse** [comment] 2021-06-17 07:39
Hi @RiotTuxedo,

I am having the same problem that is outlined in this issue. My account (Deftcorse - On the OCE server) is missing two games in the match history. I have since played another two matches which have appeared, but the other two appear lost in the void. 

Are you able to take a look when you get a chance? I couldn't find anywhere else to post this, apologies if it is the wrong forum.

Cheers,
Deftcorse

**Comment by RiotTuxedo** [comment] 2021-06-17 07:50
What's your summoner name? And confirming this is in OCE.

**Comment by Deftcorse** [comment] 2021-06-17 08:19
Summoner Name: Deftcorse
Region: OCE

https://imgur.com/a/0U3LCZk - Between the placings 3rd and 4th, there were two matches. A first and a second I believe.

Really appreciate you taking a look into this.

**Comment by RiotTuxedo** [comment] 2021-06-17 21:55
@Deftcorse we're aware of an issue where matches were lost between 6/15 and 6/16. This appears to be unrelated to the previous reports in this thread, but yes we're aware and are looking into restoring these matches and ensuring the matches aren't lost like this in the future.

**Comment by Deftcorse** [comment] 2021-06-18 00:03
No problem, apologies that the issue is unrelated to this thread. Thanks for the information!

**Comment by RiotTuxedo** [comment] 2021-06-18 00:05
There's no way you could have known it was unrelated. Mostly just commenting on the fact that this is a new separate issue. Appreciate the report since losing match history is definitely not good.

**Comment by RiotTuxedo** [comment] 2021-06-28 01:49
@Deftcorse these matches have been recovered:
OC1_455436117
OC1_455471177

**Comment by Deftcorse** [comment] 2021-06-28 07:30
Awesome - really appreciate you looking into it!

**Comment by scoob22** [comment] 2021-08-29 01:34
@RiotTuxedo Hey Mr. Tuxedo.  I'm running into this same issue on the Korean server - my ign is just scoob.  Here is my lolchess https://lolchess.gg/profile/kr/scoob.  I've been spamming games over the last couple of days since I have a ton of free time during quarantine (you'll see that reflected in the lp graph on lolchess), but most of the games are not reflected in my match history with only some of the games showing on the lolchess match history.  I'm using the en_US locale for my client - could this be part of the issue?  Let me know if I should be reaching out to someone at Riot KR if you are unable to help out with stuff on the KR server.  Very Best, Scoob

**Comment by cauchy2384** [comment] 2021-08-30 16:34
@RiotTuxedo Can confirm. Have had trouble getting the latest matches for the past couple of days.

**Comment by RiotTuxedo** [comment] 2021-08-30 17:31
@scoob22 can you be a little more specific here? Ideally, you could tell us what days, which matches (i.e. placements or other players in the same game), and the order in which those matches are missing, like so:

August 30th
match1
match2 (missing)
match3 (missing)
match4
etc

**Comment by cauchy2384** [comment] 2021-08-30 17:40
@RiotTuxedo
Summoner:  TL Snoodyboo EUW
Latest match ID from match list request: EUW1_5432124281, Thu Aug 26 
Lolchess shows matches played Aug 29. https://lolchess.gg/profile/euw/tlsnoodyboo

**Comment by RiotTuxedo** [comment] 2021-08-30 18:37
@cauchy2384 These are all matches from August 26th?

We're in the process of reconciling matches in the amercias and europe clusters. KR is in the asia cluster and currently we believe there shouldn't have been any issues updating the matchlist in the asia region.

**Comment by cauchy2384** [comment] 2021-08-30 18:48
@RiotTuxedo I think these are the last matches TL Snoodyboo played yet (Aug 28-29). I've received them from the match list of summoners he played with. They are not shown in his match list from API.

**Comment by scoob22** [comment] 2021-09-01 00:19
@RiotTuxedo Looks to be fixed - thanks for all you do!
