### ISSUE TITLE
[BUG] Third party code endpoint is returning http 404 and empty Response Body

### ISSUE THREAD

**Issue by Jankec** [RiotGames/developer-relations#323] opened 2020-06-21 12:01 UTC
**Bug Description**  
I saved the verification code in the LoL client several times but the API returned http 404 and empty Response Body

**Problem Description**  
Cannot be verify accounts

**Expected Result**  
The verification code in the Response Body. ("1234verifycationcode")

**Actual Result**  
The Response Body is empty.
![kép](https://user-images.githubusercontent.com/1475455/85223609-6fddf300-b3c4-11ea-9bff-bae94da23040.png)

**Developer Impact**
* Frequency: Every API call.

**Player Impact**
* Frequency: Every time the user try to register an account, they experiennce this issue. 
* Severity: When it happens, no one can register an account.
* Region: Tested on EUNE

**Repro Steps**
1. Open LoL client
1. Go to the Settings Menu (the gear icon in the upper right corner)
1. In the menu on the left, select "Verification". 
1. Enter the Verification Code  ("1234verifycationcode")
1. Get the encryptedSummonerId (endpoint: /lol/summoner/v4/summoners/by-name/)
1. Try to get the Verification Code (endpoint: /lol/platform/v4/third-party-code/by-summoner/)

**Issue Comments**
 It looks like the client has not saved the verification code. Or the endpoint just doesn't work.

**Comment by thomasmarton** [comment] 2020-06-21 12:12
Duplicate of #289 
I replied to your comment yesterday but apparently you ignored it.

**Comment by Jankec** [comment] 2020-06-21 12:18
That was not answer. And you just directed me where they deal with http 500, that does not detail this error

**Comment by Krissalyce** [comment] 2020-06-21 16:53
Hello good sir,

If you would use your reading eyes, you can see that the issue has been reopened by Riot Tuxedo, and that the endpoint is now returning 404s. Please fully read the content of the bug report before creating new issues or continuing this one, in order to better track and centralize the issue.

Thank you.

**Comment by Jankec** [comment] 2020-06-21 17:30
Greetings Mr,

I read every comment and I thought it was necessary to create a new issue because in vain others have written comments, no progress has been made for about 20 days.
I was hoping that if I described the problem in detail and opened a new issue specifically to this error, maybe someone would understand and progress is being made.

Thank you for your comment.

**Comment by RiotTuxedo** [comment] 2020-07-22 00:28
This issue should get resolved with patch 10.15. I'm closing this particular issue because it appears to be a duplicate of #239 and closely related to #289.

**Closed** 2020-07-22 00:28 UTC
